### ISSUE TITLE
New Layout, not working

### ISSUE THREAD

**Issue by Daiwik27** [SintcoLTD/sparxmaths#1]
will it autosolve the actuall question?

**Comment by NajmAjmal** [comment]
Hi @Daiwik27,

This repo as migrated to my github, for future issues etc, do them so [here](https://github.com/NajmAjmal/sparxmaths).

The extension currently compatible with Google Chrome, and it will allow you to Bypass bookwork codes.

Thanks, Najm

**Comment by NajmAjmal** [comment]
To continue using the extension, Download from C0lide's Repository

https://github.com/c0lide/SparxSolver
