### ISSUE TITLE
STOLEN WITHOUT CREDITS - DO NOT USE

### ISSUE THREAD

**Issue by alexlostorto** [SintcoLTD/sparxmaths#1]
# **OFFICIAL REPO** -> [https://github.com/alexlostorto/magic-notes](https://github.com/alexlostorto/magic-notes)

**ALL** code here is **WRITTEN BY ME** and both my credits and copyright have been **REMOVED WITHOUT PERMISSION**.

**Comment by SintcoLTD** [comment]
Sorry for the misunderstanding, credits were removed temporally but now have been restored.
