### ISSUE TITLE
Cannot Inject

### ISSUE THREAD

**Issue by thfc18222** [SintcoLTD/sparxmaths#10]
When ever I try to inject it into the console it gives a error saying that it can't inject.

**Comment by NajmAjmal** [comment]
Hi,

if the current inject does not work for you then paste this code into your console. It only works whilst visiting the sparxmaths website.

`s=document.createElement('script');s.src='https://cdn.jsdelivr.net/gh/SintcoLTD/sparxmaths@main/inject.js';document.head.appendChild(s);`

Thanks, Najm
