### ISSUE TITLE
how to go back to defualt theme

### ISSUE THREAD

**Issue by DevBaccon** [SintcoLTD/sparxmaths#11]
h

**Comment by NajmAjmal** [comment]
Hi @DevBaccon 

We have edited the code for the Original solver from one with colour themes, to one without. This new version of the product is called [Sintco Sparxmaths Solver VOID Edition](https://github.com/SintcoLTD/sparxmaths-void/tree/main).

I hope this resolves this issue, if not re-open it.

Thanks, Najm

**Comment by DevBaccon** [comment]
thanks broski
