### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by IFrzzl** [SintcoLTD/sparxmaths#12]
Hey all,

Loving the project, was wondering whether the Chrome extension could be ported to Firefox? I might be able to help if you're interested.

**Comment by NajmAjmal** [comment]
Hi @IFrzzl,

Thanks for your Suggestion. We currently do not support Firefox, Though we are planning to do so in the future. For other non-supported browsers, you can use our [JavaScript code Snippet](https://github.com/SintcoLTD/sparxmaths#installation). Or view custom [Firefox install instructions](https://github.com/SintcoLTD/sparxmaths/blob/main/docs/install-firefox.md).

Our current progress to add a Firefox compatible Addon is [here](https://github.com/SintcoLTD/sparxmaths/tree/sparxmaths-firefox-test).

You can help by forking the project, and adding/modify code to it. This can be by modifying some scripts to be compatible with Firefox, etc.

Thanks Najm,

**Comment by NajmAjmal** [comment]
Hi @IFrzzl,

Thanks again for your Suggestion, We have currently added some Support to Firefox. If you would like to use our Sparxmaths Solver Program, you can visit [Install Instructions Here](https://github.com/SintcoLTD/sparxmaths#installation). Click the Firefox Option.

Thanks, Najm
