### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by 0xVienna** [SintcoLTD/sparxmaths#15]
Hi not tryna cause trouble but I went fr9m yt Video And here. Is this safe?

**Comment by 0xVienna** [comment]
OMG IT WORKS 100000% RECOMMENDREKT

**Comment by NajmAjmal** [comment]
Hi, @0xVienna,

Thanks for Recommending.
I was wondering which **YouTube Video** you are referring to, if you could provide a link to it.

Thanks, Najm

**Comment by 0xVienna** [comment]
https://youtu.be/5rhpdhbkC5I

**Comment by NajmAjmal** [comment]
Thanks, for attaching the Youtube video link.

This YouTube video is not affiliated with us.

Thanks, Najm

**Comment by 0xVienna** [comment]
Ok no problem, btw I advertised this in my school server, is that ok?

**Comment by NajmAjmal** [comment]
Yes, that is ok.

But do not Advertise the YouTube video, instead do the GitHub repository directly
https://github.com/SintcoLTD/sparxmaths

Thanks, Najm

**Comment by 0xVienna** [comment]
Got it

**Comment by NajmAjmal** [comment]
If there are any further

- Problems
- Questions
- or general Queries

You can re-open this issue or create another

Thanks, Najm
