### ISSUE TITLE
when installing it doesnt give me the answer.

### ISSUE THREAD

**Issue by elpanafaus** [SintcoLTD/sparxmaths#20]
when installing it doesnt give me the answers to the questions it only changes the theme any fix to this?

**Comment by NajmAjmal** [comment]
Hi @elpanafaus,

Which install method did you use?
- Bookmarklet
- Javascript install snippet
- Browser extension

Also the extension highlights the correct Bookwork code during the bookwork check.

<p align="center">
  <img width="70%" src="https://raw.githubusercontent.com/SintcoLTD/CDN/main/chrome-extension/sparxmaths/images/bookwork-code.png">
</p>

Full [Features](https://github.com/SintcoLTD/sparxmaths#-features)

It currently does not answer Sparxmaths Questions


Thanks, Najm
