### ISSUE TITLE
What if this could do more

### ISSUE THREAD

**Issue by Toricate** [SintcoLTD/sparxmaths#21]
This is amazing and I was searching for something like this for ages but the colours aren't necessarily pretty but other then that, could you soon add where like an AI could could read questions and like answer it or something.
Thanks

**Comment by NajmAjmal** [comment]
Hi @Toricate,

Thanks for liking our program. We have thought about integrating AI features to our program, but so far we haven't.
We would appreciate any aid to grow and make this program better. You can contribute to this program by forking and submitting a **PR**.

Also, Thanks for your Suggestions. We will take them onboard and **strive** to **improve** this program more.

**Keep all your Suggestions, Improvements & anything else coming.**


Thanks, @NajmAjmal
