### ISSUE TITLE
AI integration with project

### ISSUE THREAD

**Issue by technophile32** [SintcoLTD/sparxmaths#22]
Greetings.
I would like to work on AI capabilities to the Sparxmaths solver extension, using the Microsoft Cognitive Services API (or any other feasible options that I feel should be sufficient and work). This will allow users to use AI to solve the math problems (on SparxMaths, of course) and even get explanations. I am an experienced developer who can help with this if I can get more details. 

PS: I assume you already have a written permission letter from Sparxmaths in order to comply with rules & regulations (to use their assets in own software)?

Thanks.

**Comment by NajmAjmal** [comment]
Hi @technophile32,

Feel free to fork this repo and upgrade it with AI Features. If you will need help navigating through the files or what each files does, you can open another issue.

Also this is not "Software", it is a program/JS Snippet. This is a browser extension*. This program does not use any of Sparx's software. It instead adds additional code to the website, which adds the extra [Features](https://github.com/SintcoLTD/sparxmaths#-features).

# "(to use their assets in own software)?"

We do not use any Sparx's assets in our program except for their name and website for this program, so it is recognisable and functional.

# Other
## T&C
I hope you have read our Terms and conditions before using this program.
## Stargaze
I also hope to see you with our [Stargazers](https://github.com/SintcoLTD/sparxmaths/stargazers). You can join by starring the repo.
## Other
"Sparx" refers to the company Sparx LTD, Who owns & and have created Sparxmaths.
"Our" refers to @SintcoLTD And all members within the organization or company

Also you can gather addition AI Relevant info from this issue [here](https://github.com/SintcoLTD/sparxmaths/issues/21)

*Can be used via other methods listed [here](https://github.com/SintcoLTD/sparxmaths#installation). 


Thanks, Najm

**Comment by technophile32** [comment]
Thanks for your reply. I am happy to share that I have started to work on the AI integration (believe me - it's going to get damn  complex, -probably- useless after GPT image input rolls out). It might take upto a week.

Thanks.
