### ISSUE TITLE
Sintco is not working

### ISSUE THREAD

**Issue by RohanTaheem** [SintcoLTD/sparxmaths#3]
When I get a Bookwork check nothing shows up telling me what one it is. And when I refresh the page there will  be a small black box over the first one but only ever the first one. Even if the order changes. Chrome also gives me an error. 
![image](https://github.com/SintcoLTD/sparxmaths/assets/79914499/8756b7f8-dfe5-4df9-8831-b4a17979a4ce)

**Comment by NajmAjmal** [comment]
To continue using the extension, Download from C0lide's Repository

https://github.com/c0lide/SparxSolver
