### ISSUE TITLE
Can't load unpacked

### ISSUE THREAD

**Issue by LMAOIDK12** [SintcoLTD/sparxmaths#32]
I use opera GX and followed the instructions, when i select the folder it says could not find manifest file, i also tried the bookmark method, the themes show up but the highlighted answers don't

**Comment by NajmAjmal** [comment]
Hi @LMAOIDK12

For loading the extension, make sure you have selected the extensions' folder within the main folder. In there are the extension files, as well as the manifest.json.

“the themes show up but the highlighted answers don't”. It Highlights the correct bookwork code during the bookwork check.

If this does not help re-open this issue.

Thanks, Najm
