### ISSUE TITLE
Manifest file not found

### ISSUE THREAD

**Issue by LMAOIDK12** [SintcoLTD/sparxmaths#34]
Ive already been doing what you have said, But when i open it in the normal folders, i see the manifest file, when loading unpacked, it is no longer there

**Comment by LMAOIDK12** [comment]
Oh nvm i managed to do it, but now the problem is that when im on the question, the answer is not highlighted

**Comment by LMAOIDK12** [comment]
Ah im sorry i just realised that one of the features does not include highlighting the answer it just does the bookwork code alr np

**Comment by NajmAjmal** [comment]
Hi @LMAOIDK12 

It seems you have sorted the problem out yourself.

Thanks, Najm
