### ISSUE TITLE
Confusion with Privacy Policy

### ISSUE THREAD

**Issue by hosm1002** [SintcoLTD/sparxmaths#8]
I'm just a bit concerned by this:
![image](https://user-images.githubusercontent.com/131755538/236153524-2bbd5f3c-2e14-4cd3-bc0d-7e43b1be92dc.png)
Why does it store and send login data? I may be reading it wrong, But I ask just in case.

**Comment by alexlostorto** [comment]
This issue has been answered and **closed** [here](https://github.com/alexlostorto/magic-notes/issues/8).
